// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//打包消息
func Packet(msg interface{}) (uint32, []byte, error) {
	switch msg.(type) {
	case *SRegist:
		//msg.(*SRegist).Code = 1002
		b, err := msg.(*SRegist).Marshal()
		return 1002, b, err
	case *SWxLogin:
		//msg.(*SWxLogin).Code = 1004
		b, err := msg.(*SWxLogin).Marshal()
		return 1004, b, err
	case *SLoginOut:
		//msg.(*SLoginOut).Code = 1006
		b, err := msg.(*SLoginOut).Marshal()
		return 1006, b, err
	case *SLogin:
		//msg.(*SLogin).Code = 1000
		b, err := msg.(*SLogin).Marshal()
		return 1000, b, err
	default:
		return 0, []byte{}, errors.New("unknown message")
	}
}