// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//打包消息
func Rpacket(msg interface{}) (uint32, []byte, error) {
	switch msg.(type) {
	case *CLogin:
		//msg.(*CLogin).Code = 1000
		b, err := msg.(*CLogin).Marshal()
		return 1000, b, err
	case *CRegist:
		//msg.(*CRegist).Code = 1002
		b, err := msg.(*CRegist).Marshal()
		return 1002, b, err
	case *CWxLogin:
		//msg.(*CWxLogin).Code = 1004
		b, err := msg.(*CWxLogin).Marshal()
		return 1004, b, err
	default:
		return 0, []byte{}, errors.New("unknown message")
	}
}