// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//解包消息
func Runpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 1002:
		msg := new(SRegist)
		//msg.Code = 1002
		err := msg.Unmarshal(b)
		return msg, err
	case 1004:
		msg := new(SWxLogin)
		//msg.Code = 1004
		err := msg.Unmarshal(b)
		return msg, err
	case 1006:
		msg := new(SLoginOut)
		//msg.Code = 1006
		err := msg.Unmarshal(b)
		return msg, err
	case 1000:
		msg := new(SLogin)
		//msg.Code = 1000
		err := msg.Unmarshal(b)
		return msg, err
	default:
		return nil, errors.New("unknown message")
	}
}