// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//解包消息
func Unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 1004:
		msg := new(CWxLogin)
		//msg.Code = 1004
		err := msg.Unmarshal(b)
		return msg, err
	case 1000:
		msg := new(CLogin)
		//msg.Code = 1000
		err := msg.Unmarshal(b)
		return msg, err
	case 1002:
		msg := new(CRegist)
		//msg.Code = 1002
		err := msg.Unmarshal(b)
		return msg, err
	default:
		return nil, errors.New("unknown message")
	}
}